#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
examine-sql script use exclusively for testing examine_sql
from its source tree
"""

import sys
import os
import re

import inspect

package_path = inspect.getfile(inspect.currentframe()) # script filename, may be absolute or relative
script_dir = os.path.dirname(package_path)
src = os.path.realpath(script_dir + "/../src")
package_dir = src + "/examine_sql"

if not os.path.exists(package_dir):
    raise ValueError("Package directory does not exist:  '{}'".format(package_dir))
    
sys.path.insert(0, src)

from examine_sql.main import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
